import BookCard from "../components/book-card";

function About() {
    return (
        <div className="about">
            <div className="title-section">
                <h1>About the Author</h1>
                <h3>Brian Andrew</h3>
            </div>
            <p>Lots of text goes here...Lots of text goes here...Lots of text goes here...
                Lots of text goes here...Lots of text goes here...Lots of text goes here...
                Lots of text goes here...Lots of text goes here...Lots of text goes here...
                Lots of text goes here...Lots of text goes here...Lots of text goes here...
                Lots of text goes here...Lots of text goes here...Lots of text goes here...
                Lots of text goes here...Lots of text goes here...Lots of text goes here...
                Lots of text goes here...Lots of text goes here...Lots of text goes here...</p>
            <p>Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            Need more info...Need more info...Need more info...Need more info...
            </p>
        </div>
    )
}

export default About